
var dict = {
    en: {
        'SITE-TITLE':'My name is Vitali, I am developing web sites and web presentations and other products.',
        'Purpose':'Purpose :',
        'Purse-Text':'Getting the position of Front-End developer.',
        'Professional-Skills':'Professional skills :',
        'Experience':'Experience :',
        'Experience-Content':'August 2016 - present time - front-end developer, FeelFree Inc.',
        'Functional-Responsibilities':'Functional responsibilities :',
        'Responsibilities-Text1':'Adaptive cross-browser layout of sites and landing pages.',
        'Responsibilities-Text2':'Adaptation for mobile devices.',
        'Responsibilities-Text3':'Implement "HTML" and create Wordpress themes.',
        'Work-Html': 'Coding "HTML" :',
        'Work-Examples':'Work-Examples :',
        'Themes-WordPress':'Themes "WordPress" :',
        'Applications-React':'"React" Application :',
        'Education': 'Education :',
        'Education-One': 'National Metallurgical Academy of Ukraine, Dnipro',
        'Education-Two': 'Industrial College of Ukraine, Dnipro.',
        'Personal-Qualities':'Personal qualities :',
        'Qualities-Text':'Attentiveness, responsibility, technical thinking, poise, concentration, high degree of self- organization, discipline, focus on achieving results.',
        'HEADING-ONE':'About me :',
        'SOME-TEXT':'Some text in tag P',
        'ANOTHER-TEXT':'another text1',
        'First-Name':'Vitaliy',
        'Last-Name':'Nosov',
        'Write-Me': 'WRITE ME',
        'Location':'Location :',
        'A-Country':'Ukraine',
        'City':'Dnepr',
        'Contact':'Contact :',
        'Social- Network':'Social network :',
        'languages':'Languages :',
        'English':'English',
        'Ru':'Rusian',
        'Ukr':'Ukranian',
        'Download':'Download :',
        'Email-Button' : 'Send',
        'Attach-File': 'Attach file...'



    },
    ru: {
        'SITE-TITLE': 'Меня зовут Виталий я занимаю разработкой веб-сайтов и веб-преложений и других продуктов.',
        'Purpose': 'Цель :',
        'Purse-Text': 'Получение должности Front-End разработчика.',
        'Professional-Skills': 'Профессиональные навыки :',
        'Experience': 'Опыт работы :',
        'Experience-Content': 'Август 2017 г. – наст. время – front-end developer, FeelFree Inc.',
        'Functional-Responsibilities': 'Обязанности :',
        'Responsibilities-Text1': 'Адаптивная кроссбраузерная верстка сайтов и лендинговых страниц.',
        'Responsibilities-Text2': 'Адаптирование под мобильные устройства.',
        'Responsibilities-Text3': 'Натяжка "HTML" верстки на Word Press и разработка тем.',
        'Work-Examples': 'Примеры работ :',
        'Work-Html': 'Верстка "HTML" :',
        'Themes-WordPress': 'Темы на "Word Press" :',
        'Applications-React': 'Приложение на "React" :',
        'Education': 'Образование :',
        'Education-One': 'Национальная металлургическая академия Украины, Днепр.',
        'Education-Two': 'Индустриальный коледж Украины, Днепр.',
        'Personal-Qualities': 'Личные качества :',
        'Qualities-Text': 'Внимательность, ответственность, техническое мышление, сосредоточенность, высокая степень самоорганизации, дисциплинированность, ориентированность на достижение результата.',
        'HEADING-ONE': 'Обо мне :',
        'SOME-TEXT': 'Some text in tag P',
        'ANOTHER-TEXT': 'another text1',
        'First-Name': 'Виталий',
        'Last-Name': 'Носов',
        'Write-Me': 'НАПИСАТЬ МНЕ',
        'Location': 'Местоположение :',
        'A-Country': 'Украина',
        'City': 'Днепр',
        'Contact': 'Контакты :',
        'Social- Network': 'Социальные сети :',
        'languages': 'Языки :',
        'English': 'Англисский',
        'Ru': 'Русский',
        'Ukr': 'Украинский',
        'Download': 'Скачать :',
        'Email-Button': 'Отправить',
        'Attach-File': 'Прикрепить файл...'
    }
};